export default [
  [ "2021 Autumn", {
    ids: [ [ "spotify", "5qWNmJgxmzxfviroOLTnwa" ] ],
    tracks: [
      { title: "Frozen Away", artist: "altopalo" },
      { title: "Best Friend - Be Kind Version", artist: "The Staves" },
      { title: "Talk Talk Talk - Phantogram Remix", artist: "Ilan Rubin" },
      { title: "Move into Me (feat. Broods)", artist: "Bad Sounds" },
      { title: "Maker", artist: "Hana Vu" },
      { title: "Anthem Grey", artist: "Awir Leon" },
      { title: "Came out of a Lady", artist: "Rubblebucket" },
      { title: "Jessica WJ", artist: "Cayucas" },
      { title: "This Head I Hold", artist: "Electric Guest" },
      { title: "Wallflower", artist: "Latir" },
      { title: "Chills Me to the Bone", artist: "Tricky" },
      { title: "Brown Liquor", artist: "RÜDE CÅT" },
      { title: "Silence & Secrets", artist: "WhoMadeWho" },
      { title: "Lemonade", artist: "Rubblebucket" },
      { title: "Outré Lux (feat. Madison McFerrin)", artist: "Photay" },
      { title: "Pure Heart", artist: "Martina Topley-Bird" },
      { title: "Highway 6", artist: "The Beaches" },
      { title: "Oh Devil", artist: "Electric Guest" },
      { title: "Afro Blue", artist: "Melanie De Biasio" },
      { title: "stabilise", artist: "Nilüfer Yanya" },
      { title: "Still Cold", artist: "Cleo Sol" },
      { title: "Sharpness", artist: "Jamie Woon" },
      { title: "Stranger", artist: "Gabriels" },
    ],
  } ],
  [ "2021 Summer", {
    ids: [ [ "spotify", "0n1YOf6QzNE8VpTfMX1XQC" ] ],
    tracks: [
      { title: "Tropics", artist: "Sunny & Gabe" },
      { title: "I Owe You Nothing", artist: "Seinabo Sey" },
      { title: "A Mermaid in Lisbon", artist: "Patrick Watson" },
      { title: "Lemon [Feat. Sharon Van Etten] - Kareem Ali Remix", artist: "Local Natives" },
      { title: "Parallel", artist: "Anna Mieke" },
      { title: "Arch Enemy", artist: "Everything Everything" },
      { title: "Make It", artist: "Isaac Delusion" },
      { title: "Vita", artist: "La rappresentante di lista" },
      { title: "Ordinary Boy - The Cinematic Orchestra Remix", artist: "Ultraísta" },
      { title: "I'll Never Let You Go", artist: "mmeadows" },
      { title: "Magnified", artist: "Island Police" },
      { title: "Everything Is Connected", artist: "Zara McFarlane" },
      { title: "Loud(y)", artist: "Lewis Del Mar" },
      { title: "Divisionary (Do The Right Thing)", artist: "Ages and Ages" },
      { title: "Boomerang", artist: "Yebba" },
      { title: "How Come My Body", artist: "Half Moon Run" },
      { title: "Vampire Weeknight", artist: "Jenny Owen Youngs" },
      { title: "Weather Girl", artist: "Figueroa" },
      { title: "Leave Earth", artist: "Clarence Clarity" },
      { title: "Waterfalls", artist: "SAULT" },
    ],
  } ],
  [ "2021 Spring", {
    ids: [ [ "spotify", "2QiYlXZknloNSOJK12W3GK" ] ],
    tracks: [
      { title: "Sleep On The Wing", artist: "Bibio" },
      { title: "Working For The Men", artist: "Drab City" },
      { title: "MONTERO (Call Me By Your Name)", artist: "Lil Nas X" },
      { title: "No Me Toques Mal", artist: "Santiago Navas" },
      { title: "Imagination", artist: "Jordan Rakei" },
      { title: "Good Days", artist: "SZA" },
      { title: "Festival of Panic", artist: "Y La Bamba" },
      { title: "Brown Eyed Lover", artist: "Allen Stone" },
      { title: "Strange Town", artist: "Buzzy Lee" },
      { title: "Free to Live in Colour", artist: "Pixey" },
      { title: "Lost Day", artist: "Other Lives" },
      { title: "Paraguaya", artist: "Juana Molina" },
      { title: "The Other Lover (Little Dragon & Moses Sumney)", artist: "Little Dragon" },
      { title: "Oh No", artist: "Biig Piig" },
      { title: "Happen To Me", artist: "BENEE" },
      { title: "In Your Arms", artist: "Low Island" },
      { title: "Ing-Maries vals", artist: "Sara Parkman" },
      { title: "From a Place of Love", artist: "Kele" },
      { title: "Shattering The Hourglass", artist: "Deep Sea Diver" },
      { title: "All Night", artist: "Marika Hackman" },
      { title: "Think About Things", artist: "Daði Freyr" },
      { title: "Grow", artist: "MUNA" },
      { title: "Potential Breakup Song", artist: "Aly & AJ" },
      { title: "The Rip", artist: "Portishead" },
    ],
  } ],
  [ "2021 Early Spring", {
    ids: [ [ "spotify", "3MveNGK5Lp9dL1a0KwekUj" ] ],
    tracks: [
      { title: "Villain (feat. golda may)", artist: "Photay" },
      { title: "Liberty Bell", artist: "DARKSIDE" },
      { title: "Shadow On The Sea", artist: "CHAMPS" },
      { title: "For The Sky", artist: "HAERTS" },
      { title: "Long Road Home", artist: "Oneohtrix Point Never" },
      { title: "Shadows (feat. Lou Stone)", artist: "Zero 7" },
      { title: "Orange Blossoms", artist: "Half Waif" },
      { title: "Garden of Eden", artist: "Billie Marten" },
      { title: "Nothing’s Impossible", artist: "Caroline Rose" },
      { title: "Desert Lake", artist: "Donna Blue" },
      { title: "I'll Take It Boring", artist: "Jordana" },
      { title: "Flowers To My Demons", artist: "NNAMDÏ" },
      { title: "Hypotheticals - Edit", artist: "Lake Street Dive" },
      { title: "Killer Scene", artist: "Pale Honey" },
      { title: "Hologram", artist: "Max Pope" },
      { title: "Cat's Pyjamas", artist: "Caro" },
      { title: "Light - Edit", artist: "Michael Kiwanuka" },
      { title: "Indigo Blue", artist: "Sean Christopher" },
      { title: "Sister", artist: "Caribou" },
      { title: "Call Your Name", artist: "Tora-i" },
      { title: "The Loch Ness Monster", artist: "Matilda Mann" },
      { title: "Let Me Tell You Something", artist: "Lera Lynn" },
      { title: "Lovesick", artist: "Alice Phoebe Lou" },
    ],
  } ],
  [ "2020 Winter", {
    ids: [ [ "spotify", "0ZC10mc5OKnRfBgQalr5zt" ] ],
    tracks: [
      { title: "Blue", artist: "Angelo De Augustine" },
      { title: "I Am a Joker!", artist: "BEA1991" },
      { title: "Rock Pools", artist: "Saint Saviour" },
      { title: "Pray It Away", artist: "Hannah Georgas" },
      { title: "Audacious", artist: "Ian Chang" },
      { title: "Paraphernalia", artist: "Temples" },
      { title: "Eso Que Tu Haces", artist: "Lido Pimienta" },
      { title: "Roseate", artist: "Ioanna Gika" },
      { title: "Sad Music", artist: "Jessica Winter" },
      { title: "Throw Stones", artist: "Nana Adjoa" },
      { title: "We're Just Making It Worse", artist: "Cameron Avery" },
      { title: "Don't Wanna Fight", artist: "Alabama Shakes" },
      { title: "Mountain Baby", artist: "Austra" },
      { title: "Dining With My Head at the Table", artist: "Franny London" },
      { title: "For the Time Being", artist: "Erlend Øye" },
      { title: "The Bug Collector", artist: "Haley Heynderickx" },
      { title: "You Know Where My Happiness Went", artist: "Valentina" },
      { title: "Wolves", artist: "Jensen McRae" },
      { title: "Underneath", artist: "Gracie and Rachel" },
      { title: "In Birdsong", artist: "Everything Everything" },
    ],
  } ],
  [ "2020 Autumn", {
    ids: [ [ "spotify", "5XOCOnz7nIbwKPy5krcI4J" ] ],
    tracks: [
      { title: "Coming to Get You Nowhere", artist: "This Is The Kit" },
      { title: "Thunderbird", artist: "Dessert" },
      { title: "Red Lights", artist: "SAULT" },
      { title: "Dad's Old Tapes", artist: "North Downs" },
      { title: "Woman (feat. Lianne La Havas)", artist: "Nao" },
      { title: "On My Knees (feat. Michael Kiwanuka)", artist: "UNKLE" },
      { title: "Mariana Trench", artist: "Dwara" },
      { title: "Remember Where You Are", artist: "Jessie Ware" },
      { title: "This Is How We Walk on the Moon", artist: "Arthur Russell" },
      { title: "In Your Eyes", artist: "Anjimile" },
      { title: "I Fall Asleep So Fast", artist: "Pitou" },
      { title: "Library Takeout", artist: "MicrOpaqu3" },
      { title: "Monk's Robes", artist: "Deradoorian" },
      { title: "Smoke", artist: "Jay-Jay Johanson" },
      { title: "Liar Liar Liar", artist: "St Francis Hotel" },
      { title: "Sound of Violence", artist: "Other Lives" },
      { title: "The Other Way - Chapelier Fou Remix", artist: "Awir Leon" },
      { title: "He Came from the Sun", artist: "C Duncan" },
      { title: "Feral", artist: "Elder Island" },
      { title: "Robber", artist: "The Weather Station" },
    ],
  } ],
  [ "2020 Late Summer", {
    ids: [ [ "spotify", "66PcwnCVWvc0alLJpCfsOA" ] ],
    tracks: [
      { title: "It's Love (feat. Matthew Young)", artist: "Cosmo's Midnight" },
      { title: "Fahrenheit", artist: "Kitt Philippa" },
      { title: "Bleak", artist: "Death Machine" },
      { title: "Ain't No Remedy", artist: "Love Supreme" },
      { title: "March March", artist: "The Chicks" },
      { title: "In A Bind - Strings Version", artist: "Vagabon" },
      { title: "The Atlantic", artist: "The Dodos" },
      { title: "Give a Little Love (feat. Sufjan Stevens)", artist: "Mina Tindle" },
      { title: "The Moon Shines Bright", artist: "Sam Lee" },
      { title: "Plans We Made", artist: "Son Lux" },
      { title: "Ocean Bed", artist: "Darlingside" },
      { title: "If I Wunna", artist: "Toulouse" },
      { title: "A Pleasing Smile", artist: "Aloboi" },
      { title: "The Wheel - Live with the Metropole Orkest", artist: "SOHN" },
      { title: "Lovable", artist: "Blaue Blume" },
      { title: "Check The Weather", artist: "Pavo Pavo" },
      { title: "Dive", artist: "The Seshen" },
      { title: "Sundown Queen", artist: "Buzzy Lee" },
      { title: "Nature Song", artist: "Twain" },
      { title: "rbbts", artist: "Kate Davis" },
      { title: "Such a Remarkable Day", artist: "Charlotte Gainsbourg" },
      { title: "Yellow Jacket", artist: "moa moa" },
      { title: "Bad Medication", artist: "Sophie Hunger" },
      { title: "Paris", artist: "Saint Saviour" },
      { title: "L.A. (Looking Alive)", artist: "Madison Cunningham" },
      { title: "Keep Me Close", artist: "Faces on TV" },
      { title: "Someone New", artist: "Helena Deland" },
    ],
  } ],
  [ "2020 High Summer", {
    ids: [ [ "spotify", "6MIhAmbfLBBcQ0JHUGR6z5" ] ],
    tracks: [
      { title: "Young Buck", artist: "Braids" },
      { title: "Francis", artist: "Haley Heynderickx" },
      { title: "Bruise - Piano Version", artist: "Yumi Zouma" },
      { title: "When Cameron Was in Egypt's Land Let My Cameron Go", artist: "Voka Gentle" },
      { title: "The Place I Want to Be", artist: "Saint Saviour" },
      { title: "Holiday", artist: "Steady Holiday" },
      { title: "Face of the Sun", artist: "Shana Cleveland" },
      { title: "Temple", artist: "Thao" },
      { title: "Cheater", artist: "Wilma Archer" },
      { title: "Harmony", artist: "Ultraísta" },
      { title: "Floating Heads", artist: "Sister Crayon" },
      { title: "Je k'abere", artist: "Surv" },
      { title: "No Reason", artist: "Tōth" },
      { title: "I Took A Ride", artist: "Caroline Rose" },
      { title: "Staying Awake", artist: "DM Stith" },
      { title: "Suit of Armour", artist: "Danika" },
      { title: "El Búho", artist: "Blanco White" },
      { title: "You", artist: "Kyson" },
      { title: "The Meetings of the Waters", artist: "Fionn Regan" },
      { title: "Guinevere", artist: "Black Sea Dahu" },
    ],
  } ],
  [ "2020 Spring", {
    ids: [ [ "spotify", "7piB5J6WhcjuUYkLTKaKbT" ] ],
    tracks: [
      { title: "Coast", artist: "Participant" },
      { title: "Reptilia", artist: "Andrew Combs" },
      { title: "Whole", artist: "Girlyboi" },
      { title: "Bipolar Rainbows", artist: "Clarence Clarity" },
      { title: "The Cut Girl (feat. Howard Hobbs)", artist: "Invisible Minds" },
      { title: "A Stone Is a Stone", artist: "Helena Deland" },
      { title: "Far Gone (Don't Leave)", artist: "Pictish Trail" },
      { title: "Afterlife", artist: "Public Memory" },
      { title: "Steady Waves", artist: "Cross Record" },
      { title: "Goliath", artist: "Woodkid" },
      { title: "I Want You To Love Me", artist: "Fiona Apple" },
      { title: "Looking for You", artist: "Flo Morrissey" },
      { title: "Nobody Said", artist: "Takénobu" },
      { title: "White Whale", artist: "Everything Everything" },
      { title: "You Are (feat. YVA)", artist: "Nitin Sawhney" },
      { title: "Breakfast Epiphany", artist: "Boy Azooga" },
      { title: "Shawty", artist: "Remi Wolf" },
      { title: "Everything Is Good", artist: "Sophie Hunger" },
      { title: "Human Nature", artist: "Babeheaven" },
      { title: "Infinity Vibraphones", artist: "These New Puritans" },
    ],
  } ],
  [ "2020 Early Spring", {
    ids: [ [ "spotify", "2F4CZdQo3BzHfA33OywUcM" ] ],
    tracks: [
      { title: "Blood Red", artist: "The Colorist Orchestra" },
      { title: "Calm Down", artist: "The Clementines" },
      { title: "Just Before Dawn", artist: "Sonnymoon" },
      { title: "Lange Vinnen", artist: "Eefje de Visser" },
      { title: "Red White and Black", artist: "Jesca Hoop" },
      { title: "Give Me an Answer", artist: "Low Roar" },
      { title: "Have to Be Around You", artist: "Brooke Bentham" },
      { title: "Search For Life", artist: "Dirty Projectors" },
      { title: "bye bye, sun francisco", artist: "Lor" },
      { title: "Hard Time", artist: "Seinabo Sey" },
      { title: "Virtuous Circle", artist: "Jordan Klassen" },
      { title: "Vasco da Gama", artist: "Colapesce" },
      { title: "Tuesday Afternoon", artist: "A House In The Trees" },
      { title: "When Will I Belong", artist: "Geographer" },
      { title: "Living", artist: "TENDER" },
      { title: "My Best Self", artist: "Half Waif" },
      { title: "Need Your Love", artist: "Tennis" },
      { title: "Sea of Wine", artist: "Teleman" },
      { title: "Token", artist: "Panda Bear" },
      { title: "Suspicious", artist: "Faces on TV" },
    ],
  } ],
  [ "2019 Winter", {
    ids: [ [ "spotify", "5duwOVJxIpUA8AaDF8S2pU" ] ],
    tracks: [
      { title: "1000 Words", artist: "0171" },
      { title: "Ruins", artist: "aYia" },
      { title: "By Your Side", artist: "French 79" },
      { title: "Retribution", artist: "Sucre" },
      { title: "Swimmers", artist: "Zero 7" },
      { title: "Origami", artist: "Totemo" },
      { title: "Vide Noir", artist: "Lord Huron" },
      { title: "I Adore", artist: "Laura Misch" },
      { title: "Lover", artist: "Árstíðir" },
      { title: "Sapphire", artist: "Diamond Thug" },
      { title: "Drastic Measures", artist: "Bayonne" },
      { title: "Canopée", artist: "Polo & Pan" },
      { title: "Disarray", artist: "Low" },
      { title: "Time", artist: "EMEFE" },
      { title: "Speak Loud", artist: "Trills" },
      { title: "The Visitor", artist: "Kadhja Bonet" },
      { title: "I'm That Guy", artist: "Agar Agar" },
      { title: "Freedom Falls", artist: "Khushi" },
      { title: "I Don't Know", artist: "WhoMadeWho" },
      { title: "There Is Still Pain Left", artist: "Sophie Hunger" },
    ],
  } ],
  [ "2019 Autumn", {
    ids: [ [ "spotify", "2hBpcdpOgi4ptUmZtFyysq" ] ],
    tracks: [
      { title: "Devil's Sweetheart", artist: "Alice Phoebe Lou" },
      { title: "Miles Away", artist: "Alex Ebert" },
      { title: "Spiral", artist: "Wye Oak" },
      { title: "Moonshine", artist: "Caravan Palace" },
      { title: "Every Note", artist: "Mystery Skulls" },
      { title: "Bottom Of The Deep Blue Sea", artist: "MISSIO" },
      { title: "Thumbnail", artist: "Louie Zong" },
      { title: "still feel.", artist: "half•alive" },
      { title: "Siamo ospiti", artist: "La rappresentante di lista" },
      { title: "My Type", artist: "Saint Motel" },
      { title: "Foreign Bodies", artist: "Lucy Swann" },
      { title: "Movies", artist: "Weyes Blood" },
      { title: "Attack Sustain Release", artist: "Chrome Sparks" },
      { title: "One Eye Open", artist: "O Mer" },
      { title: "home with you", artist: "FKA twigs" },
      { title: "Fragment II", artist: "Drinker" },
      { title: "The Ceremony Of Innocence", artist: "Moby" },
      { title: "CARONTE", artist: "Apparat" },
      { title: "Run Me Through - King Princess Remix", artist: "Perfume Genius" },
      { title: "I Love You, But I Need Another Year", artist: "Liza Anne" },
    ],
  } ],
  [ "2019 Summer", {
    ids: [ [ "spotify", "0iDI01sNxtjfFyvAqms3vK" ] ],
    tracks: [
      { title: "Heavy Cross", artist: "Gossip" },
      { title: "Half Asleep", artist: "Yeasayer" },
      { title: "Oasis", artist: "Jordan Rakei" },
      { title: "I Want It All", artist: "Shey Baba" },
      { title: "Hot For The Mountain", artist: "Natalie Prass" },
      { title: "Horse to Water", artist: "Tall Heights" },
      { title: "Ophelia", artist: "George Taylor" },
      { title: "The Good Part", artist: "Liz Lawrence" },
      { title: "Redwood Tree", artist: "Jamie Drake" },
      { title: "High", artist: "Lokki" },
      { title: "Sweet Hell", artist: "Maiah Manser" },
      { title: "Two Wooden Spoons", artist: "This Is The Kit" },
      { title: "Genghis Khan", artist: "Miike Snow" },
      { title: "High", artist: "ooi" },
      { title: "Fynbos - Mahogany Sessions", artist: "Alice Phoebe Lou" },
      { title: "Line Lie", artist: "Violents" },
      { title: "Bad Habits", artist: "Madame Gandhi" },
      { title: "May", artist: "Jordan Rakei" },
      { title: "Handmade Ego", artist: "TENDER" },
      { title: "Tiger", artist: "Joon Moon" },
    ],
  } ],
  [ "2019 Spring", {
    ids: [ [ "spotify", "0qEiJWBvMPpf8CrpEyOcLh" ] ],
    tracks: [
      { title: "Sparrow", artist: "Simon & Garfunkel" },
      { title: "Teardrops", artist: "Peter and Kerry" },
      { title: "Dream Sweet in Sea Major", artist: "Miracle Musical" },
      { title: "Evolve", artist: "Phoria" },
      { title: "Love Crimes", artist: "Hayden Thorpe" },
      { title: "On the Air", artist: "O Mer" },
      { title: "Wedding Daze", artist: "Daniel Wilson" },
      { title: "Reoccurring Dream", artist: "Ethan Gruska" },
      { title: "All I Wanted", artist: "Hannah Cohen" },
      { title: "L'aérogramme de Los Angeles", artist: "Woodkid" },
      { title: "From Fire", artist: "Perta" },
      { title: "Yeah I Care", artist: "Nick Murphy" },
      { title: "Black Widow", artist: "Isaac Delusion" },
      { title: "See The Light", artist: "Electric Guest" },
      { title: "You Got Love", artist: "Upstairs Open" },
      { title: "UFOF", artist: "Big Thief" },
      { title: "King of Shadow", artist: "Kat Cunning" },
      { title: "Falsetto", artist: "Chris Thile" },
      { title: "Swimming Backwards", artist: "There" },
      { title: "Cruel World", artist: "Active Child" },
    ],
  } ],
  [ "2018 Winter", {
    ids: [ [ "spotify", "2WUMzCWav76j816Iy7HlS7" ] ],
    tracks: [
      { title: "Heaven's Gate", artist: "Dawn Landes" },
      { title: "Whippoorwill", artist: "Darlingside" },
      { title: "Sweet Like Brandy", artist: "Kwamie Liv" },
      { title: "Joy", artist: "Loma" },
      { title: "Sparkle", artist: "aYia" },
      { title: "Fight to Make It Up", artist: "Takénobu" },
      { title: "Tightrope", artist: "Ness Nite" },
      { title: "Addict", artist: "La Chica" },
      { title: "Nuggets", artist: "Catastrophe" },
      { title: "Sway", artist: "My Brightest Diamond" },
      { title: "Manners", artist: "Jelani Blackman" },
      { title: "Shelter", artist: "Broken Bells" },
      { title: "Heavy", artist: "First Breath After Coma" },
      { title: "Family", artist: "Pi Ja Ma" },
      { title: "Gold", artist: "Slugabed" },
      { title: "Here and Heaven", artist: "Stuart Duncan" },
      { title: "The Lily", artist: "Blanco White" },
      { title: "Without Words", artist: "Joseph of Mercury" },
      { title: "New", artist: "Alex Stolze" },
      { title: "One", artist: "Cleo Sol" },
    ],
  } ],
  [ "2018 Autumn", {
    ids: [ [ "spotify", "4hz15AHUl7Jh2wOlo3WZim" ] ],
    tracks: [
      { title: "Circles", artist: "Acollective" },
      { title: "Ensen Dhaif", artist: "Emel" },
      { title: "Sanctify", artist: "Years & Years" },
      { title: "Vertigo", artist: "Shey Baba" },
      { title: "Every Animal", artist: "Half Waif" },
      { title: "Yellow Dust", artist: "Miink" },
      { title: "Losing You", artist: "Gizmo Varillas" },
      { title: "Anthem", artist: "O Mer" },
      { title: "Salam - Original Mix", artist: "Mashrou' Leila" },
      { title: "Fall", artist: "Lisa Hannigan" },
      { title: "Miami (feat. BIA)", artist: "Kali Uchis" },
      { title: "Too Fast", artist: "Sonder" },
      { title: "Bitter Winter", artist: "ALASKALASKA" },
      { title: "Mockingbird", artist: "Uma" },
      { title: "Remind Me", artist: "Emily King" },
      { title: "Body", artist: "Julia Jacklin" },
      { title: "Everybody Loves You", artist: "SOAK" },
      { title: "Churchyard", artist: "AURORA" },
      { title: "Sun Is Rising", artist: "Otzeki" },
      { title: "Half Life", artist: "Oh Pep!" },
      { title: "Hollow Days", artist: "Twin Shadow" },
      { title: "Inner G", artist: "Low Leaf" },
      { title: "Can You Hear Me - Rework", artist: "Amber Mark" },
      { title: "Feel Your Weight - Poolside Remix", artist: "Rhye" },
      { title: "Mystery", artist: "Fabiana Palladino" },
      { title: "IM U", artist: "Beacon" },
      { title: "Cruel", artist: "Monica Martin" },
      { title: "Demolition Man", artist: "Rizzle Kicks" },
      { title: "Drumsolo", artist: "Leyya" },
      { title: "We Should Be Holding Hands", artist: "Blonde Redhead" },
      { title: "ZeroFrame", artist: "When Saints Go Machine" },
    ],
  } ],
  [ "2018 Summer", {
    ids: [ [ "spotify", "5dXOReQ13ONoj8YpnjZyKK" ] ],
    tracks: [
      { title: "Borders", artist: "St. Beauty" },
      { title: "The Fog", artist: "Overcoats" },
      { title: "Valerians", artist: "Vasser" },
      { title: "Flashlight", artist: "Örvar Smárason" },
      { title: "Birdie Bees", artist: "Gavin Turek" },
      { title: "20/20 (Amelia)", artist: "Hannah Epperson" },
      { title: "Un4gvn (feat. Two Beards)", artist: "Ruby Friedman" },
      { title: "Inside", artist: "Sucre" },
      { title: "Thunderbird", artist: "Evil" },
      { title: "Elijah (feat. Laura Mvula and Jay Prince)", artist: "House of EL" },
      { title: "Gravity Don't Pull Me", artist: "Rostam" },
      { title: "The Wandering Star", artist: "Saintseneca" },
      { title: "Little Woman", artist: "Twin Shadow" },
      { title: "The Whole Summer", artist: "Lo-Fang" },
      { title: "Taste - Recorded at Spotify Studios NYC", artist: "Rhye" },
      { title: "Frikii", artist: "iZem" },
      { title: "When The Body Is Gone - SA TA NA MA DEMO", artist: "Nick Mulvey" },
      { title: "Rank & File", artist: "Moses Sumney" },
      { title: "Crimson Eyes", artist: "Roxanne Tataei" },
      { title: "Superior (Fuck You)", artist: "Schmieds Puls" },
      { title: "Broken Arrow", artist: "Francis Novotny" },
      { title: "Death Spiral", artist: "Dirty Projectors" },
      { title: "Oatmeal", artist: "Sudan Archives" },
      { title: "Nylon", artist: "Kllo" },
      { title: "Strangest Of Ways", artist: "Lucy Rose" },
      { title: "Garden", artist: "Jono McCleery" },
      { title: "All the Way Home", artist: "Bokanté" },
      { title: "ASTROTHUNDER", artist: "Travis Scott" },
      { title: "Sinking Ship", artist: "Wild Child" },
      { title: "Regina", artist: "Becca Stevens" },
      { title: "Driving Down to L.A", artist: "Ezra Furman" },
      { title: "Rebel Heart", artist: "First Aid Kit" },
      { title: "All My Life", artist: "The Staves" },
      { title: "Ivy - Throwing Snow Remix", artist: "Tusks" },
    ],
  } ],
  [ "2018 Spring", {
    ids: [ [ "spotify", "1N0IMpvAxd2FFlf6E0WOqX" ] ],
    tracks: [
      { title: "Again", artist: "Timmies" },
      { title: "Yemaya", artist: "Kele" },
      { title: "Good Kisser", artist: "Lake Street Dive" },
      { title: "The Pharmacist", artist: "Groeni" },
      { title: "NorthSea", artist: "Solregn" },
      { title: "Paramount Tether", artist: "Febueder" },
      { title: "In a Girls World", artist: "Saint Michel" },
      { title: "Animal Games", artist: "The Colorist Orchestra" },
      { title: "A Step (feat. Pete Josef)", artist: "Manu Delago" },
      { title: "1-800-273-8255", artist: "Logic" },
      { title: "the baptist", artist: "Lauren Auder" },
      { title: "Honey", artist: "Kehlani" },
      { title: "Sky Walker - Recorded at Spotify Studios NYC", artist: "Miguel" },
      { title: "hard rain", artist: "Lykke Li" },
      { title: "Hans", artist: "Febueder" },
      { title: "Boys", artist: "Charli XCX" },
      { title: "Golden Wings", artist: "Gabriel Garzón-Montano" },
      { title: "Short Court Style", artist: "Natalie Prass" },
      { title: "Keep Running ...and Running", artist: "New Venusians" },
      { title: "Root", artist: "Sonnymoon" },
    ],
  } ],
  [ "2017 Winter", {
    ids: [ [ "spotify", "7yDjTvpNgmNP0qOsC4zSOB" ] ],
    tracks: [
      { title: "Escapements", artist: "Beacon" },
      { title: "Vow", artist: "TENDER" },
      { title: "How Far", artist: "Tei Shi" },
      { title: "Under", artist: "Sampha" },
      { title: "Wallowa Lake Monster", artist: "Sufjan Stevens" },
      { title: "Dangerous", artist: "Son Lux" },
      { title: "Underwaterfall", artist: "Bearcubs" },
      { title: "Severed Logic", artist: "Half Waif" },
      { title: "S P A C E", artist: "Amber Mark" },
      { title: "Parking Lot", artist: "Anderson .Paak" },
      { title: "Passionfruit", artist: "Drake" },
      { title: "Lonely World", artist: "Moses Sumney" },
      { title: "Make Me Feel", artist: "Janelle Monáe" },
      { title: "Try", artist: "Jelani Blackman" },
      { title: "Painted Blue", artist: "Jono McCleery" },
      { title: "Mortal Man", artist: "Camarano" },
      { title: "Hold Us Down", artist: "Fyfe" },
      { title: "Wonder Eyes", artist: "bailey" },
      { title: "Emaille", artist: "Anna Rune" },
      { title: "DISRESPECT IS UNIVERSAL", artist: "Jenny Wilson" },
    ],
  } ],
  [ "2017 Autumn", {
    ids: [ [ "spotify", "47BwEHh2yhF1hPUoP6gQoR" ] ],
    tracks: [
      { title: "Neighbors", artist: "Grizzly Bear" },
      { title: "Bad Place For A Good Time", artist: "Kae Tempest" },
      { title: "A Thousand Cracks", artist: "Lambert" },
      { title: "Heartbeat", artist: "Zola Blood" },
      { title: "In My Bed", artist: "Deep Throat Choir" },
      { title: "four ethers", artist: "serpentwithfeet" },
      { title: "Anoche", artist: "Arca" },
      { title: "To The Moon And Back", artist: "Fever Ray" },
      { title: "Every Little Thing", artist: "Röyksopp" },
      { title: "Stuck with Me", artist: "The Neighbourhood" },
      { title: "Benighted", artist: "Keep Shelly In Athens" },
      { title: "True Care", artist: "James Vincent McMorrow" },
      { title: "33 “GOD”", artist: "Bon Iver" },
      { title: "Choir", artist: "Perfume Genius" },
      { title: "We Choose", artist: "Her" },
      { title: "Rennen", artist: "SOHN" },
      { title: "Pencils", artist: "ANIMA!" },
      { title: "Feel It Still", artist: "Portugal. The Man" },
      { title: "Fear & Force", artist: "Vagabon" },
      { title: "Ribbon", artist: "Billie Marten" },
    ],
  } ],
  [ "2017 Summer", {
    ids: [ [ "spotify", "5zy4MyCbLKCnGeNWpAvOrm" ] ],
    tracks: [
      { title: "No Shortcuts", artist: "Heather Maloney & Darlingside" },
      { title: "Paperwalls", artist: "Andreya Triana" },
      { title: "What It's Worth", artist: "Elder Island" },
      { title: "Face", artist: "Christian Rich" },
      { title: "Jimmy Franco", artist: "Lolawolf" },
      { title: "Is It Because You Know I Love You", artist: "Len Sander" },
      { title: "Maghawir", artist: "Mashrou' Leila" },
      { title: "Deep Green", artist: "Marika Hackman" },
      { title: "August In Paris", artist: "Sage" },
      { title: "Keep On Running", artist: "Gabriel Garzón-Montano" },
      { title: "Stoned on You", artist: "Jaymes Young" },
      { title: "Blood Moon", artist: "M. Craft" },
      { title: "Hudea", artist: "Inude" },
      { title: "Meet Me There", artist: "Nick Mulvey" },
      { title: "Outside Things", artist: "Charlie Cunningham" },
      { title: "Chalk", artist: "Blanco White" },
      { title: "I Can't Help It", artist: "Soft Lit" },
      { title: "Never Met You", artist: "Laskaar" },
      { title: "Come Along", artist: "Cosmo Sheldrake" },
      { title: "Put Castle", artist: "The/Das" },
    ],
  } ],
  [ "2017 Spring", {
    ids: [ [ "spotify", "4xEhOpUOQ6yyVvb5crxBgU" ] ],
    tracks: [
      { title: "Islands of You and Me", artist: "Maia Vidal" },
      { title: "In God's House", artist: "Bat For Lashes" },
      { title: "Myth", artist: "Tsar B" },
      { title: "Verse", artist: "Rhye" },
      { title: "Everything Is Free", artist: "Gillian Welch" },
      { title: "Armour", artist: "TENDER" },
      { title: "Watercolor Dreams", artist: "Shy Girls" },
      { title: "With You", artist: "James Supercave" },
      { title: "Caving", artist: "Seavera" },
      { title: "The Deserters", artist: "Rachel Zeffira" },
      { title: "Everlasting Sigh", artist: "Moses Sumney" },
      { title: "Under Water", artist: "Baby Alpaca" },
      { title: "Hot Coals", artist: "Edward Sharpe & The Magnetic Zeros" },
      { title: "Bodies - Sin Fang Remix", artist: "Farao" },
      { title: "Ridin' Round (Sky High)", artist: "Fatima" },
      { title: "The Highway", artist: "Tunde Olaniran" },
      { title: "Fire", artist: "Lowly" },
      { title: "Virtue", artist: "Yates" },
      { title: "Silver", artist: "Lo-Fang" },
      { title: "So Long", artist: "Jono McCleery" },
    ],
  } ],
  [ "2016 Winter", {
    ids: [ [ "spotify", "1PHStfnp3e2fRjr1Qa6o4t" ] ],
    tracks: [
      { title: "Stronger - Acoustic", artist: "Fyfe" },
      { title: "Run Run Run", artist: "The Notwist" },
      { title: "Shine Again", artist: "Kutiman" },
      { title: "Glimpse of Hope", artist: "Nils Bech" },
      { title: "Loveless", artist: "Wild Ones" },
      { title: "Blood I Bled", artist: "The Staves" },
      { title: "Easy To Read", artist: "Milk & Bone" },
      { title: "To Get By", artist: "Empress Of" },
      { title: "Bullets", artist: "Archive" },
      { title: "A Mess Like This", artist: "The Dø" },
      { title: "Murmuration", artist: "Nomad Soul" },
      { title: "Empty", artist: "Eva + Manu" },
      { title: "Wood", artist: "Rostam" },
      { title: "Up In Hudson - edit", artist: "Dirty Projectors" },
      { title: "Life Is a Liquid", artist: "Exec" },
      { title: "Glamour", artist: "George Cosby" },
      { title: "Underwater", artist: "Porches" },
      { title: "Five Minutes", artist: "Her" },
      { title: "To See You Smile", artist: "Yuksek" },
      { title: "In Denial", artist: "William Ryan Fritch" },
    ],
  } ],
  [ "2016 Autumn", {
    ids: [ [ "spotify", "4g6ESOpEp6hgbbwDWxIRaG" ] ],
    tracks: [
      { title: "Hiding In The Rushes", artist: "Francesca Belmonte" },
      { title: "White Fox in the Snow", artist: "Grapell" },
      { title: "Tape2Tape (feat. Joel Compass)", artist: "Aqualung" },
      { title: "Land Of All", artist: "Woodkid" },
      { title: "Undone", artist: "Phoria" },
      { title: "September", artist: "Robot Koch" },
      { title: "How to Waste a Moment", artist: "James Vincent McMorrow" },
      { title: "Irredeemer", artist: "Ed Tullett" },
      { title: "Polly", artist: "Gem Club" },
      { title: "Airport", artist: "The Attic Sleepers" },
      { title: "Calm It Down", artist: "Sisyphus" },
      { title: "For", artist: "C Duncan" },
      { title: "Generation Blue", artist: "Niia" },
      { title: "Kill Your Mama", artist: "Alicia Keys" },
      { title: "Almost Makes Me Wish for Rain", artist: "Lucius" },
      { title: "Jaigantic", artist: "Tora" },
      { title: "I Left You", artist: "Arthur Beatrice" },
      { title: "Phoenix", artist: "Kill J" },
      { title: "By the Way", artist: "Scott Orr" },
      { title: "Conversations", artist: "Fyfe" },
    ],
  } ],
  [ "2016 Summer", {
    ids: [ [ "spotify", "5rQyKWfbWwOLZo41sTnX6R" ] ],
    tracks: [
      { title: "Aftermath", artist: "Hundreds" },
      { title: "Sirens", artist: "Lola Marsh" },
      { title: "Bright Luck", artist: "Portico" },
      { title: "Walk On Water", artist: "Kat Dahlia" },
      { title: "The Pretender", artist: "Tessa Rose Jackson" },
      { title: "Now I'm Alive", artist: "O Mer" },
      { title: "Slowbirth", artist: "Elsiane" },
      { title: "Reconfiguration", artist: "Other Lives" },
      { title: "Bloom - Wife Remix", artist: "Talos" },
      { title: "Emily", artist: "San Fermin" },
      { title: "Play Out", artist: "Zola Blood" },
      { title: "We're So Light", artist: "Hook & The Twin" },
      { title: "Marz", artist: "John Grant" },
      { title: "TC and Honeybear", artist: "John Grant" },
      { title: "Down On My Luck", artist: "VIC MENSA" },
      { title: "Seesaw", artist: "Club Kuru" },
      { title: "Shores - Orchestral", artist: "WE ARE MATCH" },
      { title: "Turn To Dust", artist: "Wolf Alice" },
      { title: "Take Your Face Off", artist: "Lydia Ainsworth" },
      { title: "Sleep Baby Sleep", artist: "BROODS" },
    ],
  } ],
  [ "2016 Spring", {
    ids: [ [ "spotify", "5Sow5ETIAc9HbFZ4HTBCyE" ] ],
    tracks: [
      { title: "What You Don't Do", artist: "Lianne La Havas" },
      { title: "Some Minds (feat. Andrew Wyatt)", artist: "Flume" },
      { title: "Feel", artist: "Dead Times" },
      { title: "I Tried", artist: "Lucy Rose" },
      { title: "Volcano - feat. Phoene Somsavath", artist: "Saycet" },
      { title: "Double Dolphins On the Nickel", artist: "Mice Parade" },
      { title: "Lessons", artist: "SOHN" },
      { title: "Someone New", artist: "KANEHOLLER" },
      { title: "Pulsing (feat. Nina K)", artist: "Tomas Barfod" },
      { title: "Take Me", artist: "Sisyphus" },
      { title: "To Pluto's Moon - Son Lux Remix", artist: "My Brightest Diamond" },
      { title: "All These Years", artist: "Shivum Sharma" },
      { title: "Family", artist: "Apothek" },
      { title: "Metamorphosis", artist: "Wyles & Simpson" },
      { title: "Cry No More", artist: "Vaults" },
      { title: "Seconds", artist: "Ghost Loft" },
      { title: "Dark Days", artist: "HUGOwho" },
      { title: "Late Visitor", artist: "Chilly Gonzales" },
      { title: "Why Don't You Save Me?", artist: "Kan Wakan" },
      { title: "Dead Arms & Dead Legs", artist: "Eliot Sumner" },
    ],
  } ],
  [ "2015 Winter", {
    ids: [ [ "spotify", "6Ext9arH0jdh0MQQ7ondJz" ] ],
    tracks: [
      { title: "Turn Away", artist: "Beck" },
      { title: "The Other Side", artist: "French For Rabbits" },
      { title: "Somewhere Else", artist: "INDIANS" },
      { title: "Breadwinner", artist: "BEA1991" },
      { title: "Fire Rides", artist: "MØ" },
      { title: "Nile", artist: "Douglas Dare" },
      { title: "Everybody's Got To Learn Sometime", artist: "The Field" },
      { title: "The Knower", artist: "Youth Lagoon" },
      { title: "Fame", artist: "The Acid" },
      { title: "Hunter", artist: "Farao" },
      { title: "The Monster", artist: "Atella" },
      { title: "Memex", artist: "Duologue" },
      { title: "Forever (feat. Lucinda)", artist: "Nomad Soul" },
      { title: "Clockwork", artist: "Douglas Dare" },
      { title: "The Love You Have in You", artist: "Asbjørn" },
      { title: "Secret", artist: "Huntington" },
      { title: "Exxus", artist: "Glass Animals" },
      { title: "Marilyn Monroe", artist: "Sevdaliza" },
      { title: "To Build A Home", artist: "The Cinematic Orchestra" },
      { title: "Warm on a Cold Night", artist: "HONNE" },
    ],
  } ],
  [ "2015 Autumn", {
    ids: [ [ "spotify", "5LeLZ4L9GqOXFK2T7IeHh0" ] ],
    tracks: [
      { title: "Neither Here Nor There", artist: "Lost In The Trees" },
      { title: "Pressure", artist: "My Brightest Diamond" },
      { title: "Pressure", artist: "Until The Ribbon Breaks" },
      { title: "Dust It Off", artist: "The Dø" },
      { title: "Kanye", artist: "Bogan Via" },
      { title: "True Love", artist: "Montag" },
      { title: "Drown", artist: "Marika Hackman" },
      { title: "Technicolour Beat", artist: "Oh Wonder" },
      { title: "No Harm Is Done (feat. Tunji Ige)", artist: "Christine and the Queens" },
      { title: "River from the Sky", artist: "The Weepies" },
      { title: "Doing the Wrong Thing", artist: "Kaki King" },
      { title: "Speaking Of Truth - Orchestrated", artist: "Laleh" },
      { title: "Do You Remember", artist: "Jarryd James" },
      { title: "Wandering Back", artist: "Sucre" },
      { title: "I See I Say", artist: "Ebony Bones!" },
      { title: "City Of Sin", artist: "Linus Young" },
      { title: "Line Of Fire", artist: "Junip" },
      { title: "Beneath the Brine", artist: "The Family Crest" },
      { title: "Fuel to Fire", artist: "Agnes Obel" },
      { title: "The Big Idea", artist: "Black Books" },
    ],
  } ],
  [ "2015 Summer", {
    ids: [ [ "spotify", "01dQyfJIETrWbNYrE3Br7D" ] ],
    tracks: [
      { title: "Try To Be", artist: "Blue Hawaii" },
      { title: "My Song 5", artist: "HAIM" },
      { title: "Make It Holy", artist: "The Staves" },
      { title: "Wait for a Minute", artist: "Tune-Yards" },
      { title: "Ghosting", artist: "Mother Mother" },
      { title: "Russia", artist: "Ramona Falls" },
      { title: "Jo", artist: "Goldfrapp" },
      { title: "4th and Roebling", artist: "The Districts" },
      { title: "Iamundernodisguise", artist: "School Of Seven Bells" },
      { title: "Hey Now", artist: "London Grammar" },
      { title: "6 8", artist: "Gabriel Garzón-Montano" },
      { title: "Tongues", artist: "Joywave" },
      { title: "I Want a House", artist: "Mr Twin Sister" },
      { title: "Sonsick", artist: "San Fermin" },
      { title: "Can't Go Back", artist: "Phil Beaudreau" },
      { title: "Tempest", artist: "SOHN" },
      { title: "Midnight Moon", artist: "Waterstrider" },
      { title: "Float", artist: "FTSE" },
      { title: "Bitch", artist: "Allie X" },
      { title: "Drowning", artist: "BANKS" },
    ],
  } ],
];
