export default [

{ name: "Rider",
  number: 1,
  suit: "9 of ♥︎",
  meanings: [ "energy", "passion", "speed", "activity", "news", "messages" ],
},

{ name: "Clover",
  number: 2,
  suit: "6 of ♦︎",
  meanings: [ "luck", "lightheartedness", "small happinesses", "opportunity", "being untroubled", "comedy" ],
},

{ name: "Ship",
  number: 3,
  suit: "Banner of ♠︎",
  meanings: [ "departure", "farewell", "distance", "voyage", "travel", "journey", "adventure", "trading" ],
},

{ name: "House",
  number: 4,
  suit: "King of ♥︎",
  meanings: [ "home", "establishment", "safety", "tradition", "custom", "privacy", "conservation", "what is under your roof" ],
},

{ name: "Tree",
  number: 5,
  suit: "7 of ♥︎",
  meanings: [ "health", "growth", "grounded", "past connection", "personal growth", "spirituality", "family/ancestors" ],
},

{ name: "Cloud",
  number: 6,
  suit: "King of ♣︎",
  meanings: [ "confusion", "lack of clarity", "misunderstanding", "insecurity", "doubt", "hidden secrets" ],
},

{ name: "Snake",
  number: 7,
  suit: "Queen of ♣︎",
  meanings: [ "desire", "seduction", "deception", "craving", "attraction", "sexuality", "wisdom", "forbidden knowledge" ],
},

{ name: "Coffin",
  number: 8,
  suit: "9 of ♦︎",
  meanings: [ "ending", "dying", "funeral", "loss", "grief", "mourning", "sadness", "ill health" ],
},

{ name: "Bouquet",
  number: 9,
  suit: "Queen of ♠︎",
  meanings: [ "flattery", "social life", "pleasantness", "cordiality etiquette", "politeness", "appreciation", "beauty", "art", "an unexpected gift" ],
},

{ name: "Scythe",
  number: 10,
  suit: "Jack of ♦︎",
  meanings: [ "accidents", "hasty decisions", "danger", "a warning", "speed", "reckoning", "a decision that cannot be undone" ],
},

{ name: "Whip",
  number: 11,
  suit: "Jack of ♣︎",
  meanings: [ "conflict", "discussions", "arguments", "debate", "scolding", "opposition", "objection", "violence", "repetitive actions", "sexual behaviour" ],
},

{ name: "Birds",
  number: 12,
  suit: "7 of ♣︎",
  meanings: [ "worry", "excitement", "gossip", "chattering", "nervousness", "anxiety", "an old couple", "conversation in-person" ],
},

{ name: "Child",
  number: 13,
  suit: "Jack of ♠︎",
  meanings: [ "new beginnings", "child", "toddler", "play ", "inexperience", "innocence", "immaturity", "small", "new", "vulnerable" ],
},

{ name: "Fox",
  number: 14,
  suit: "9 of ♣︎",
  meanings: [ "selfishness", "self care", "trickery", "suspicion", "cunning", "caution" ],
},

{ name: "Bear",
  number: 15,
  suit: "Banner of ♣︎",
  meanings: [ "power", "leadership", "dominance", "influence", "short temper", "strength of character", "boss", "matriarch", "hirsuit", "a body builder or over-weight person" ],
},

{ name: "Star",
  number: 16,
  suit: "6 of ♥︎",
  meanings: [ "hope", "inspiration", "optimism", "spirituality", "dreams", "progress to goals" ],
},

{ name: "Stork",
  number: 17,
  suit: "Queen of ♥︎",
  meanings: [ "change", "transition", "movement", "recurrence", "new cycle", "yearning" ],
},

{ name: "Dog",
  number: 18,
  suit: "Banner of ♥︎",
  meanings: [ "loyalty", "friendship", "a follower", "devotion", "obedience", "support" ],
},

{ name: "Tower",
  number: 19,
  suit: "6 of ♠︎",
  meanings: [ "authority", "solitude", "loneliness", "isolation", "aloofness", "ego", "arrogance" ],
},

{ name: "Garden",
  number: 20,
  suit: "8 of ♠︎",
  meanings: [ "public affairs", "society", "culture", "teamwork", "fame", "social networks" ],
},

{ name: "Mountain",
  number: 21,
  suit: "8 of ♣︎",
  meanings: [ "difficulties", "problems", "obstacles", "impairment", "hurdles", "struggles", "challenge" ],
},

{ name: "Crossroads",
  number: 22,
  suit: "Queen of ♦︎",
  meanings: [ "choices", "many opportunities", "travel", "separation", "hesitation", "decisions" ],
},

{ name: "Mouse",
  number: 23,
  suit: "7 of ♣︎",
  meanings: [ "dwindling", "deficiency", "depletion", "destruction", "defect", "flaw", "disease" ],
},

{ name: "Heart",
  number: 24,
  suit: "Jack of ♥︎",
  meanings: [ "love", "amicability", "romanticization", "forgiveness", "reconciliation", "softness", "charity" ],
},

{ name: "Ring",
  number: 25,
  suit: "Deuce of ♣︎",
  meanings: [ "commitment", "promise", "honor", "partnership", "cooperation", "cycles" ],
},

{ name: "Book",
  number: 26,
  suit: "Banner of ♦︎",
  meanings: [ "secrets", "knowledge", "education", "information", "research", "studies" ],
},

{ name: "Letter",
  number: 27,
  suit: "7 of ♠︎",
  meanings: [ "document", "email", "speech", "conversations", "expression", "information", "communication" ],
},

{ name: "Man",
  number: 28,
  suit: "Deuce of ♥︎",
  meanings: [ "querent if male", "male friend", "partner", "family member" ],
},

{ name: "Woman",
  number: 29,
  suit: "Deuce of ♠︎",
  meanings: [ "querent if female", "female friend", "partner", "family member" ],
},

{ name: "Lilies",
  number: 30,
  suit: "King of ♠︎",
  meanings: [ "sensuality", "sex", "virtue", "morality", "ethics", "wisdom" ],
},

{ name: "Sun",
  number: 31,
  suit: "Deuce of ♦︎",
  meanings: [ "happiness", "victory", "success", "power", "warmth", "truth" ],
},

{ name: "Moon",
  number: 32,
  suit: "8 of ♥︎",
  meanings: [ "subconscious", "intuition", "emotions", "fears", "desires", "fantasy" ],
},

{ name: "Key",
  number: 33,
  suit: "8 of ♦︎",
  meanings: [ "openness", "revelation", "unlocking", "achievement", "liberation", "resolution" ],
},

{ name: "Fish",
  number: 34,
  suit: "King of ♦︎",
  meanings: [ "finances", "business", "wealth", "values", "gain", "abundance" ],
},

{ name: "Anchor",
  number: 35,
  suit: "9 of ♠︎",
  meanings: [ "stability", "restraint", "security", "resilience", "durability", "laying foundations" ],
},

{ name: "Cross",
  number: 36,
  suit: "6 of ♣︎",
  meanings: [ "duty", "conviction", "suffering", "burden", "intolerance", "principles", "indoctrination" ],
},

];
