export default [

{ name: "Rider",
  number: 1,
  suit: "9 of ♥︎",
  meanings: [ "Energy", "Passion", "Speed", "Activity", "News", "Messages" ],
},

{ name: "Clover",
  number: 2,
  suit: "6 of ♦︎",
  meanings: [ "Luck", "Lightheartedness", "Small Happinesses", "Opportunity", "Being Untroubled", "Comedy" ],
},

{ name: "Ship",
  number: 3,
  suit: "Banner of ♠︎",
  meanings: [ "Departure", "Farewell", "Distance", "Voyage", "Travel", "Journey", "Adventure", "Trading" ],
},

{ name: "House",
  number: 4,
  suit: "King of ♥︎",
  meanings: [ "Home", "Establishment", "Safety", "Tradition", "Custom", "Privacy", "Conservation", "What is Under your Roof" ],
},

{ name: "Tree",
  number: 5,
  suit: "7 of ♥︎",
  meanings: [ "Health", "Growth", "Grounded", "Past Connection", "Personal Growth", "Spirituality", "Family/Ancestors" ],
},

{ name: "Cloud",
  number: 6,
  suit: "King of ♣︎",
  meanings: [ "Confusion", "Lack of clarity", "Misunderstanding", "Insecurity", "Doubt", "Hidden Secrets" ],
},

{ name: "Snake",
  number: 7,
  suit: "Queen of ♣︎",
  meanings: [ "Desire", "Seduction", "Deception", "Craving", "Attraction", "Sexuality", "Wisdom", "Forbidden Knowledge" ],
},

{ name: "Coffin",
  number: 8,
  suit: "9 of ♦︎",
  meanings: [ "Ending", "Dying", "Funeral", "Loss", "Grief", "Mourning", "Sadness", "Ill Health" ],
},

{ name: "Bouquet",
  number: 9,
  suit: "Queen of ♠︎",
  meanings: [ "Flattery", "Social Life", "Pleasantness", "Cordiality Etiquette", "Politeness", "Appreciation", "Beauty", "Art", "An Unexpected Gift" ],
},

{ name: "Scythe",
  number: 10,
  suit: "Jack of ♦︎",
  meanings: [ "Accidents", "Hasty Decisions", "Danger", "A Warning", "Speed", "Reckoning", "A Decision that Cannot be Undone" ],
},

{ name: "Whip",
  number: 11,
  suit: "Jack of ♣︎",
  meanings: [ "Conflict", "Discussions", "Arguments", "Debate", "Scolding", "Opposition", "Objection", "Violence", "Repetitive Actions", "Sexual Behaviour" ],
},

{ name: "Birds",
  number: 12,
  suit: "7 of ♣︎",
  meanings: [ "Worry", "Excitement", "Gossip", "Chattering", "Nervousness", "Anxiety", "An Old Couple", "Conversation In-Person" ],
},

{ name: "Child",
  number: 13,
  suit: "Jack of ♠︎",
  meanings: [ "New Beginnings", "Child", "Toddler", "Play ", "Inexperience", "Innocence", "Immaturity", "Small", "New", "Vulnerable" ],
},

{ name: "Fox",
  number: 14,
  suit: "9 of ♣︎",
  meanings: [ "Selfishness", "Self Care", "Trickery", "Suspicion", "Cunning", "Caution" ],
},

{ name: "Bear",
  number: 15,
  suit: "Banner of ♣︎",
  meanings: [ "Power", "Leadership", "Dominance", "Influence", "Short temper", "Strength of character", "Boss", "Matriarch", "Hirsuit", "a Body Builder or Over-weight Person" ],
},

{ name: "Star",
  number: 16,
  suit: "6 of ♥︎",
  meanings: [ "Hope", "Inspiration", "Optimism", "Spirituality", "Dreams", "Progress to Goals" ],
},

{ name: "Stork",
  number: 17,
  suit: "Queen of ♥︎",
  meanings: [ "Change", "Transition", "Movement", "Recurrence", "New Cycle", "Yearning" ],
},

{ name: "Dog",
  number: 18,
  suit: "Banner of ♥︎",
  meanings: [ "Loyalty", "Friendship", "A Follower", "Devotion", "Obedience", "Support" ],
},

{ name: "Tower",
  number: 19,
  suit: "6 of ♠︎",
  meanings: [ "Authority", "Solitude", "Loneliness", "Isolation", "Aloofness", "Ego", "Arrogance" ],
},

{ name: "Garden",
  number: 20,
  suit: "8 of ♠︎",
  meanings: [ "Public Affairs", "Society", "Culture", "Teamwork", "Fame", "Social Networks" ],
},

{ name: "Mountain",
  number: 21,
  suit: "8 of ♣︎",
  meanings: [ "Difficulties", "Problems", "Obstacles", "Impairment", "Hurdles", "Struggles", "Challenge" ],
},

{ name: "Crossroads",
  number: 22,
  suit: "Queen of ♦︎",
  meanings: [ "Choices", "Many Opportunities", "Travel", "Separation", "Hesitation", "Decisions" ],
},

{ name: "Mouse",
  number: 23,
  suit: "7 of ♣︎",
  meanings: [ "Dwindling", "Deficiency", "Depletion", "Destruction", "Defect", "Flaw", "Disease" ],
},

{ name: "Heart",
  number: 24,
  suit: "Jack of ♥︎",
  meanings: [ "Love", "Amicability", "Romanticization", "Forgiveness", "Reconciliation", "Softness", "Charity" ],
},

{ name: "Ring",
  number: 25,
  suit: "Deuce of ♣︎",
  meanings: [ "Commitment", "Promise", "Honor", "Partnership", "Cooperation", "Cycles" ],
},

{ name: "Book",
  number: 26,
  suit: "Banner of ♦︎",
  meanings: [ "Secrets", "Knowledge", "Education", "Information", "Research", "Studies" ],
},

{ name: "Letter",
  number: 27,
  suit: "7 of ♠︎",
  meanings: [ "Document", "Email", "Speech", "Conversations", "Expression", "Information", "Communication" ],
},

{ name: "Man",
  number: 28,
  suit: "Deuce of ♥︎",
  meanings: [ "Querent if Male", "Male Friend", "Partner", "Family Member" ],
},

{ name: "Woman",
  number: 29,
  suit: "Deuce of ♠︎",
  meanings: [ "Querent if Female", "Female Friend", "Partner", "Family Member" ],
},

{ name: "Lilies",
  number: 30,
  suit: "King of ♠︎",
  meanings: [ "Sensuality", "Sex", "Virtue", "Morality", "Ethics", "Wisdom" ],
},

{ name: "Sun",
  number: 31,
  suit: "Deuce of ♦︎",
  meanings: [ "Happiness", "Victory", "Success", "Power", "Warmth", "Truth" ],
},

{ name: "Moon",
  number: 32,
  suit: "8 of ♥︎",
  meanings: [ "Subconscious", "Intuition", "Emotions", "Fears", "Desires", "Fantasy" ],
},

{ name: "Key",
  number: 33,
  suit: "8 of ♦︎",
  meanings: [ "Openness", "Revelation", "Unlocking", "Achievement", "Liberation", "Resolution" ],
},

{ name: "Fish",
  number: 34,
  suit: "King of ♦︎",
  meanings: [ "Finances", "Business", "Wealth", "Values", "Gain", "Abundance" ],
},

{ name: "Anchor",
  number: 35,
  suit: "9 of ♠︎",
  meanings: [ "Stability", "Restraint", "Security", "Resilience", "Durability", "Laying Foundations" ],
},

{ name: "Cross",
  number: 36,
  suit: "6 of ♣︎",
  meanings: [ "Duty", "Conviction", "Suffering", "Burden", "Intolerance", "Principles", "Indoctrination" ],
},

];
